name: setup
description: Runs steps to setup build environment

inputs:
  job_name:
    description: The name of the job
    default: preflight
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
      with:
        experimental: true
        reshim: true

    - name: Corepack enable
      run: corepack enable
      shell: bash

    - name: Runner image version
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}" >> "$GITHUB_ENV"
      shell: bash

    - name: Enable caching for python
      # left out due to having their own caching: yarn, node_modules, mise
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/uv
        key: py-${{ env.IMAGE_OS_VERSION }}-${{ matrix.task-name }}-${{ hashFiles('uv.lock', '.python-version') }}

    - name: Enable caching for pre-commit
      if: ${{ inputs.jop_name == 'lint' || inputs.job_name == 'preflight' }}
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
